name: Auto Sync Release

on:
    release:
        types: [created]  # Trigger on new releases in the 'ccs' repo        
    repository_dispatch:  # Optional if you want to manually trigger
    workflow_dispatch:    # Optional if you want to manually trigger
jobs:
  sync-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/checkout@v3 
      - name: Setup git & gh
        run: |
            sudo apt-get update && sudo apt-get install git
            echo ${{ secrets.GH_AUTH_TOKEN }} | gh auth login --with-token
  
      - name: Get Latest Tag from Source Repository
        id: get_latest_release
        run: |
          latestTag=$(gh release view --repo zhorton34/ccs --json tagName -q ".tagName")
          echo "Latest Tag in Source Repo: $latestTag"
          echo "::set-output name=latest_tag::$latestTag" 
      
      - name: Sync Release
        run: |
          mkdir -p tmp
          gh release download ${{ steps.get_latest_release.outputs.latest_tag }} --repo zhorton34/ccs --dir=tmp
          gh release create ${{ steps.get_latest_release.outputs.latest_tag }} --repo zhorton34/ccs-releases --title "Release ${{ steps.get_latest_release.outputs.latest_tag }}" --notes "Automatically synced from zhorton34/ccs" tmp/*
          rm -rf tmp

      - name: Update releases.json
        run: |
            # 1. Download releases.json
            curl -L -o releases.json https://github.com/zhorton34/ccs/releases/download/${{ env.latestTag }}/latest.json

            # 2. Replace repo URLs
            sed -i 's/github.com\/zhorton34\/ccs/github.com\/zhorton34\/ccs-releases/g' releases.json

            # 3. Cat releases.json file
            cat releases.json

            # 4. Commit and push
            git config --global user.name 'zhorton34'
            git config --global user.email 'zhorton999@gmail.com'
            git add releases.json
            git commit -m "Update releases.json for ${{ env.latestTag }}"
            git push origin gh-pages
  