name: Sync Release

on: [push, workflow_dispatch]

jobs:
    sync-releases:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
    
          - name: Setup GitHub CLI
            run: |
              echo ${{ secrets.GH_AUTH_TOKEN }} | gh auth login --with-token
              gh repo view --json name -q ".name"
              gh auth status
              latestTag=$(gh release view --repo zhorton34/ccs --json tagName -q ".tagName")
              hasLatestTag=$(gh release view --repo zhorton34/ccs-releases --json tagName -q ".tagName")
              echo $latestTag
              gh release download $latestTag --repo zhorton34/ccs --dir=tmp
              # gh release create $latestTag --repo zhorton34/ccs-releases --title "Release $latestTag" --notes "Automatically synced from zhorton34/ccs"
              gh release upload $latestTag --repo zhorton34/ccs-releases tmp/
          
          # Clean up downloaded files
          - name: Cleanup Artifacts
            run: rm -rf tmp