name: Sync Release

on: [push, workflow_dispatch]

jobs:
    sync-releases:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
    
          - name: Setup GitHub CLI
            run: |
              echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
    
          - name: Download  ccs release artifacts
            run: |
              latestTag=$(gh release view --repo zhorton34/ccs --json tagName -q ".tagName")
              hasLatestTag=$(gh release view --repo zhorton34/ccs-releases --json tagName -q ".tagName")
              
              if [[ "$latestTag" == "$hasLatestTag" ]]; then
                echo "Latest tag $latestTag already exists in target repository"
                exit 0
              fi

              gh release download $latestTag --repo zhorton34/ccs --dir=tmp
              gh release create $latestTag --repo zhorton34/ccs-releases --title "Release $latestTag" --notes "Automatically synced from zhorton34/ccs"
              gh release upload $latestTag --repo zhorton34/ccs-releases tmp/
          
          # Clean up downloaded files
          - name: Cleanup Artifacts
            run: rm -rf tmp