name: Sync Release

on: [push, workflow_dispatch]

jobs:
    sync-releases:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
    
          - name: Setup GitHub CLI
            run: |
              echo ${{ secrets.GH_AUTH_TOKEN }} | gh auth login --with-token
              gh repo view --json name -q ".name"          