name: Sync Releases From Private to Public Repo

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh

      - name: Authenticate GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GITHUB_TOKEN" | gh auth login --with-token

      - name: Use GitHub CLI
        run: |
          # Example: Create an issue
          gh issue create --title "New Issue" --body "Issue created from GitHub CLI in Actions"

      # Additional steps where you can use 'gh' commands...
